### PR TITLE
Revert "feat: luarocks support"

### PR DESCRIPTION
**Pull request by sergii4**
Reverts nvim-neotest/neotest-go#88

[Failed](https://github.com/nvim-neotest/neotest-go/actions/runs/8970442540) run.

@mrcjkb could please take a look?

### CODE REVIEW

**Comment by mrcjkb** [comment]
Hey :wave: 

It's failing because the release-please workflow needs a github token.
I had set `token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}`.

You can follow [this guide](https://github.com/nvim-neorocks/sample-luarocks-plugin?tab=readme-ov-file#generating-a-pat-personal-access-token) to generate a token and add it to this repo's secrets, it should fix the error (note that the guide names it `PAT` instead of `GH_TOKEN_FOR_UPDATES`).

**Comment by mrcjkb** [comment]
> @mrcjkb what about
> 
> ```
> Unexpected input(s) 'package-name', valid inputs are ['token', 'release-type',
> ```

:thinking: I suppose the `package-name` input is no longer used and can be removed.
But it's just a warning, it [won't lead to a failure](https://github.com/nvim-neorocks/rocks.nvim/actions/runs/8891485216/job/24413547304).

**Comment by sergii4** [comment]
@mrcjkb I don't have an access to the repo settings
@akinsho @rcarriga could you please take a look?

**Comment by sergii4** [comment]
I will revert it so far

**Comment by rcarriga** [comment]
Just did this recently so copied what I did (I was using semantic-release in other repos) and then added a `LUAROCKS_API_KEY` for the neotest luarocks account https://github.com/nvim-neotest/neotest-go/pull/92

@sergii4 since you're maintainer of this repo, if you'd prefer a different approach, feel free to alter. The secret will be available for you to use anyway

**Comment by rcarriga** [comment]
Sorry I mean you can edit the workflow if you'd like, the secret `LUAROCKS_API_KEY` will be available to use, you don't need to edit the secrets.

If you don't have any particular opinion on it, you can also just merge. I don't think there's any meaningful difference between semantic-release and release-please

**Comment by rcarriga** [comment]
Also looks like the tests are failing which will block releases with the current setup FYI

**Pull request merged**
