### PR TITLE
feat: refactor layout

### PR DESCRIPTION
**Pull request by Davincible**
3 things here)
1. Allow for custom hex colors in user config
2. Easily add new colorization with Lua patterns (multi group capture support)
3. Refactored the code a bit, as I found it easier to work with

Mandatory screenshot;
image

You can now define highlights like this

```lua
    -- Patterns to colorize in output
	colors = {
		run = { pattern = '(===%s+RUN)%s+(.*)', gui = { '#777777', '#deb887' }, term = { 34, 34 } },
		file = { pattern = '^%s+(.*.go):(%d+):', gui = { '#20b2aa', '#a474dc' }, term = { 36, 35 } },
		pass = { pattern = '^---%s+PASS:', gui = '#14D000', term = 31 },
		fail = { pattern = '^---%s+FAIL:', gui = '#cc0000', term = 32 },
		skip = { pattern = '^---%s+SKIP:', gui = '#729fcf', term = 33 },
	},
```

Currently only allows users to tweak colors, not define custom highlights. Option to add patterns could be exposed

### CODE REVIEW

**Comment by Davincible** [comment]
Still need to update docs

**Review by akinsho — CHANGES_REQUESTED** [review]
@Davincible thanks for the PR the idea looks good. This PR is quite hard to review though since it refactors the structure of the plugin, so seeing just what changes you needed to make for your addition is hard and any number of things could have broken or changed subtly and not be caught in a review.

I recommend either removing the refactoring or splitting that out into another PR first, so it can be discussed there, then follow it up later with this addition.

**Comment by Davincible** [comment]
I'll see what I can do. Refactoring only consisted of copying some functions into other files though, so as long as they are called properly (which I think they are), everything should work

**Comment by Davincible** [comment]
@akinsho I've removed my color changes. Functionality should be the same as before now. Functions are pulled out into separate files.

Could you have a look and merge this if you agree with it?

**Review by akinsho — CHANGES_REQUESTED** [review]
@Davincible tbh I think moving things into many smaller files feels a little bit like a lateral move, i.e. not sure things are more understandable now, but I don't mind the changes in general.

One thing I think should be fixed since there's no CI or autoformatting setup is that there is mixed indentation, i.e. some files are indented with tabs and others with spaces.

Can you change all the formatting to just use what it was originally, e.g. 2 spaces?

**Comment by Davincible** [comment]
@akinsho I felt like it was easier to work with smaller files to conceptually understand what's where, felt less cluttered, which was my reasoning for separating them out. Especially in the beginning while trying to understand the code and find where I needed to be to make the relevant changes.

You're right about the formatting, I've copied over the stylua.toml file from the neotest core to here, so it's all the same.

**Review by akinsho — APPROVED** [review]
LGTM 👍🏿

**Pull request merged**
